# Generated by Django 5.1.7 on 2025-03-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.CharField(editable=False, max_length=21, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.CharField(max_length=18)),
                ('high', models.CharField(max_length=18)),
                ('low', models.CharField(max_length=18)),
                ('close', models.CharField(max_length=18)),
                ('volume', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
